create table IF NOT EXISTS GENRES
(
    GENRE       CHARACTER VARYING(45)   not null,
    GENRE_ID    BIGINT                  generated by default as identity,
    constraint "GENRE_pk"
        primary key (GENRE_ID)
);
