server:
  port: ${SERVICE_PORT:7081}
logging:
  file:
    name: spring2026pd.log
spring:
  jpa:
    show-sql: true
  application:
    locale: ru-RU #en-US
    name: spring2026pd
  shell:
    interactive:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  data:
    rest:
      basePath: /datarest
  jmx:
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
  issuer: spring2026pd
  access-ttl-minutes: 30

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

genres-service:
  base-url: ${GENRES_SERVICE_BASE_URL:http://localhost:7082}

app:
  kafka:
    genre-create-topic: ${KAFKA_GENRE_CREATE_TOPIC:genre.create}
