create table IF NOT EXISTS GENRES
(
    GENRE       CHARACTER VARYING(45)   not null,
    GENRE_ID    BIGINT                  generated by default as identity,
    constraint "GENRE_pk"
        primary key (GENRE_ID)
);

create table IF NOT EXISTS AUTHORS
(
    AUTHOR_ID   BIGINT                  generated by default as identity,
    NAME        CHARACTER VARYING(45)   not null,
    SURNAME     CHARACTER VARYING(45)   not null,
    BIRTHDAY    DATE                    not null,
    constraint "AUTHOR_ID_pk"
        primary key (AUTHOR_ID)
);

create table IF NOT EXISTS BOOKS
(
    BOOK_ID      BIGINT                 generated by default as identity,
    NAME         CHARACTER VARYING(45)  not null,
    DESCRIPTION  CHARACTER VARYING(200),
    RELEASE_DATE DATE                   not null,
    AUTHOR_ID    BIGINT                 not null,
    GENRE_ID     BIGINT                 not null,
    constraint "BOOKS_pk"
    primary key (BOOK_ID),
    constraint "BOOKS_AUTHORS_null_fk"
    foreign key (AUTHOR_ID) references AUTHORS,
    constraint "BOOKS_GENRE_null_fk"
    foreign key (GENRE_ID) references GENRES
    );
