create table IF NOT EXISTS AUTHORS
(
    AUTHOR_ID   BIGINT                  generated by default as identity,
    NAME        CHARACTER VARYING(45)   not null,
    SURNAME     CHARACTER VARYING(45)   not null,
    BIRTHDAY    DATE                    not null,
    constraint "AUTHOR_ID_pk"
        primary key (AUTHOR_ID)
);

create table IF NOT EXISTS BOOKS
(
    BOOK_ID      BIGINT                 generated by default as identity,
    NAME         CHARACTER VARYING(45)  not null,
    DESCRIPTION  CHARACTER VARYING(200),
    RELEASE_DATE DATE                   not null,
    AUTHOR_ID    BIGINT                 not null,
    GENRE_ID     BIGINT                 not null,
    constraint "BOOKS_pk"
    primary key (BOOK_ID),
    constraint "BOOKS_AUTHORS_null_fk"
    foreign key (AUTHOR_ID) references AUTHORS,
    constraint "BOOKS_GENRE_ID_nn" check (GENRE_ID is not null)
);

create table IF NOT EXISTS COMMENTS
(
    COMMENT_ID   BIGINT                    generated by default as identity,
    COMMENT      CHARACTER VARYING(200)    not null,
    BOOK_ID         BIGINT                    not null,
    constraint "COMMENT_ID_pk"
    primary key (COMMENT_ID),
    constraint "COMMENT_BOOK_null_fk"
    foreign key (BOOK_ID) references BOOKS
);

create table IF NOT EXISTS USERS
(
    USER_ID     BIGINT                  generated by default as identity,
    USERNAME    CHARACTER VARYING(100)  not null,
    PASSWORD    CHARACTER VARYING(100)  not null,
    ENABLED     BOOLEAN                 not null default true,
    ROLE        CHARACTER VARYING(50)   not null,
    constraint "USERS_pk"
        primary key (USER_ID),
    constraint "USERS_USERNAME_uk"
        unique (USERNAME)
);
