INSERT INTO GENRES (GENRE_ID, GENRE) VALUES (1, 'Комедия');
INSERT INTO AUTHORS (AUTHOR_ID, NAME, SURNAME, BIRTHDAY) VALUES (1, 'G', 'G', DATE '2000-01-01');
INSERT INTO BOOKS (BOOK_ID, GENRE_ID, AUTHOR_ID, NAME, DESCRIPTION, RELEASE_DATE)
VALUES (1, 1, 1, 'book G', 'description G', DATE '2000-01-01');
INSERT INTO COMMENTS (COMMENT_ID, COMMENT, BOOK_ID) VALUES (1, 'first comment', 1);

INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, ENABLED, ROLE)
VALUES (1, 'user', '{noop}password', true, 'ROLE_USER');
